// new booking
export const BOOKING_REQUEST = 'BOOKING_REQUEST'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'

// booking details
export const BOOKING_DETAILS_REQUEST = 'BOOKING_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_FAIL'

// email based booking
export const EMAIL_BOOKING_REQUEST = 'EMAIL_BOOKING_REQUEST'
export const EMAIL_BOOKING_SUCCESS = 'EMAIL_BOOKING_SUCCESS'
export const EMAIL_BOOKING_FAIL = 'EMAIL_BOOKING_FAIL'

// all booking
export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST'
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS'
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'