export const PAYMENT_REQUEST = 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'

export const STRIPE_API_REQUEST = 'STRIPE_API_REQUEST'
export const STRIPE_API_SUCCESS = 'STRIPE_API_SUCCESS'
export const STRIPE_API_FAIL = 'STRIPE_API_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'