// places
export const PLACES_REQUEST = 'PLACES_REQUEST'
export const PLACES_SUCCESS = 'PLACES_SUCCESS'
export const PLACES_FAIL = 'PLACES_FAIL'

// place details
export const PLACE_REQUEST = 'PLACE_REQUEST'
export const PLACE_SUCCESS = 'PLACE_SUCCESS'
export const PLACE_FAIL = 'PLACE_FAIL'

// put booked date
export const BOOKED_DATE_PUT_REQUEST = 'BOOKED_DATE_PUT_REQUEST'
export const BOOKED_DATE_PUT_SUCCESS = 'BOOKED_DATE_PUT_SUCCESS'
export const BOOKED_DATE_PUT_FAIL = 'BOOKED_DATE_PUT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'